### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by IgorHalfeld** [vuejs-br/vedobot#1]
# Importantes
- [ ] Contar piadas
- [x] Zuar os manolos
- [ ] Fazer bule
# Não tão importantes
- [x] Votar em sugestão
- [ ] Filtro por data
- [ ] Filtro por autor
- [x] Auto upgrade
- [x] Feedback caso o que for remover não exista
- [ ] Saber qual autor aceitou a sugestão
- [x] Exclui um post caso já tenha passado da data
- [x] Comandos pelo private
